In [3]:
#1. Split this string

In [4]:
s = 'Hi there Sam!'

In [11]:
#2. Use .format() to print the following string.
#Output should be: The diameter of Earth is 12742 kilometers.

In [12]:
s.split()

['Hi', 'there', 'Sam!']

In [13]:
planet = "Earth"
diameter = 12742

In [14]:
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


In [15]:
#3. In this nest dictionary grab the word "hello"

In [16]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [17]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [18]:
#4.1 Create an array of 10 zeros?

In [22]:
import numpy as np

In [24]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
#4.2 Create an array of 10 fives?

In [26]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [27]:
#5. Create an array of all the even integers from 20 to 35

In [28]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 30 to 70")
print(array) 

Array of all the even integers from 30 to 70
[20 22 24 26 28 30 32 34]


In [29]:
#6. Create a 3x3 matrix with values ranging from 0 to 8

In [30]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [45]:
#7. Concatinate a and b

In [46]:
import numpy as np
  
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
  
new = np.concatenate((a, b), axis = 0)
  
print (new)

[1 2 3 4 5 6]


In [47]:
#6. Create a dataframe with 3 rows and 2 columns

In [48]:
import pandas as pd
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [49]:
#9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [50]:
pd.date_range(start="2023-01-01",end="2023-02-10")

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

In [53]:
#10. Create 2D list to DataFrame
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [62]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns =['S.No.', 'Name', 'Age'], dtype = int)
print(df)

   S.No. Name  Age
0      1  aaa   22
1      2  bbb   25
2      3  ccc   24


C:\Users\91948\AppData\Local\Temp\ipykernel_20204\1580403774.py:3: FutureWarning: Could not cast to int32, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised.
  df = pd.DataFrame(lists, columns =['S.No.', 'Name', 'Age'], dtype = int)
